DEPTH = ../../../../..

include $(DEPTH)/make/openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
EXE_TARGET 		= Template
EXE_TARGET_INSTALL   	= Template

####
#
#  C/CPP files
#
####

FILES 	= Template
CLFILES	= Template_Kernels.cl

include $(DEPTH)/make/openclsdkrules.mk 

