DEPTH = ../../../../..

include $(DEPTH)/make/openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
EXE_TARGET 		= DeviceFission11Ext
EXE_TARGET_INSTALL   	= DeviceFission11Ext

####
#
#  C/CPP files
#
####

FILES 	= DeviceFission11Ext
CLFILES	= DeviceFission11Ext_Kernels.cl

LLIBS  += SDKUtil

include $(DEPTH)/make/openclsdkrules.mk 

