DEPTH = ../../../../..

include $(DEPTH)/make/openclsdkdefs.mk 

####
#
#  Targets
#
####

OPENCL			= 1
SAMPLE_EXE		= 1
EXE_TARGET 		= TemplateC
EXE_TARGET_INSTALL   	= TemplateC

####
#
#  C/CPP files
#
####

FILES 	= TemplateC
CLFILES	= TemplateC_Kernels.cl

include $(DEPTH)/make/openclsdkrules.mk 

