DEPTH = ../../../..

include $(DEPTH)/make/openclsdkdefs.mk 

SUBDIRS = HelloCL \
	  GaussianNoise \
	  MatrixMulDouble \
	  SobelFilterImage \
	  HDRToneMapping \
	  URNGNoiseGL \
	  DwtHaar1DCPPKernel \
	  TransferOverlapCPP \
	  EigenValue       \
	  FFT \
	  MersenneTwister \
	  MatrixMultiplicationCPPKernel \
	  HistogramAtomics
          
include $(DEPTH)/make/openclsdkrules.mk 

